# SQL Dump for wgtimelines module
# PhpMyAdmin Version: 4.0.4
# http://www.phpmyadmin.net
#
# Host: localhost
# Generated on: Sat Oct 01, 2016 to 05:42:17
# Server version: 5.7.11
# PHP Version: 5.6.19

#
# Structure table for `wgtimelines_timelines` 6
#

CREATE TABLE `wgtimelines_timelines` (
  `tl_id` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tl_name` VARCHAR(200) NOT NULL DEFAULT '',
  `tl_weight` INT(8) NOT NULL DEFAULT '0',
  `tl_template` INT(8) NOT NULL DEFAULT '0',
  `tl_sortby` INT(1) NOT NULL DEFAULT '0',
  `tl_online` INT(1) NOT NULL DEFAULT '0',
  `tl_submitter` INT(8) NOT NULL DEFAULT '0',
  `tl_date_create` INT(8) NOT NULL DEFAULT '0',
  PRIMARY KEY (`tl_id`)
) ENGINE=InnoDB;

#
# Structure table for `wgtimelines_items` 10
#

CREATE TABLE `wgtimelines_items` (
  `item_id` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `item_tl_id` INT(8) NOT NULL DEFAULT '0',
  `item_title` VARCHAR(200) NOT NULL DEFAULT '',
  `item_content` TEXT NOT NULL,
  `item_image` VARCHAR(200) NOT NULL DEFAULT '',
  `item_date` INT(8) DEFAULT NULL,
  `item_year` INT(8) DEFAULT NULL,
  `item_weight` INT(8) NOT NULL DEFAULT '0',
  `item_submitter` INT(8) NOT NULL DEFAULT '0',
  `item_date_create` INT(8) NOT NULL DEFAULT '0',
  PRIMARY KEY (`item_id`)
) ENGINE=InnoDB;

#
# Structure table for `wgtimelines_templates` 7
#

CREATE TABLE `wgtimelines_templates` (
  `tpl_id` INT(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `tpl_name` VARCHAR(100) NOT NULL DEFAULT '',
  `tpl_desc` TEXT NOT NULL,
  `tpl_file` VARCHAR(100) NOT NULL DEFAULT '',
  `tpl_options` TEXT NOT NULL,
  `tpl_weight` INT(8) NOT NULL DEFAULT '0',
  PRIMARY KEY (`tpl_id`)
) ENGINE=InnoDB;

#
# add default templates
#

INSERT INTO `wgtimelines_templates` (`tpl_id`, `tpl_name`, `tpl_desc`, `tpl_file`, `tpl_options`, `tpl_weight`) VALUES
(1, 'Table', '<ul><li>Responsive table, based on bootstrap</li><li>Responsive images in bootstrap styles</li><li>Position of images/text selectable</li></ul>', 'wgtimelines_timelines_table.tpl', 'a:25:{i:0;a:4:{s:4:"name";s:9:"tabletype";s:5:"valid";i:1;s:5:"value";s:7:"striped";s:4:"type";s:4:"text";}i:1;a:4:{s:4:"name";s:9:"panel_pos";s:5:"valid";i:1;s:5:"value";s:9:"alternate";s:4:"type";s:4:"text";}i:2;a:4:{s:4:"name";s:12:"panel_imgpos";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:3;a:4:{s:4:"name";s:8:"imgstyle";s:5:"valid";i:1;s:5:"value";s:11:"img-rounded";s:4:"type";s:4:"text";}i:4;a:4:{s:4:"name";s:7:"bgcolor";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:5:"color";}i:5;a:4:{s:4:"name";s:9:"fontcolor";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:5:"color";}i:6;a:4:{s:4:"name";s:10:"badgestyle";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:7;a:4:{s:4:"name";s:10:"badgecolor";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:5:"color";}i:8;a:4:{s:4:"name";s:14:"badgefontcolor";s:5:"valid";i:0;s:5:"value";s:7:"#eeeeee";s:4:"type";s:5:"color";}i:9;a:4:{s:4:"name";s:9:"linecolor";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:5:"color";}i:10;a:4:{s:4:"name";s:11:"borderwidth";s:5:"valid";i:0;s:5:"value";s:3:"1px";s:4:"type";s:4:"text";}i:11;a:4:{s:4:"name";s:11:"borderstyle";s:5:"valid";i:0;s:5:"value";s:5:"solid";s:4:"type";s:4:"text";}i:12;a:4:{s:4:"name";s:11:"bordercolor";s:5:"valid";i:0;s:5:"value";s:7:"#eeeeee";s:4:"type";s:5:"color";}i:13;a:4:{s:4:"name";s:12:"borderradius";s:5:"valid";i:0;s:5:"value";s:3:"5px";s:4:"type";s:4:"text";}i:14;a:4:{s:4:"name";s:9:"boxshadow";s:5:"valid";i:0;s:5:"value";s:23:"5px 5px 5px 5px #eeeeee";s:4:"type";s:4:"text";}i:15;a:4:{s:4:"name";s:11:"orientation";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:16;a:4:{s:4:"name";s:10:"datesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:17;a:4:{s:4:"name";s:11:"issuesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:18;a:4:{s:4:"name";s:18:"issuestransparency";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:19;a:4:{s:4:"name";s:23:"issuestransparencyspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:20;a:4:{s:4:"name";s:8:"autoplay";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:21;a:4:{s:4:"name";s:17:"autoplaydirection";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:22;a:4:{s:4:"name";s:13:"autoplaypause";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:23;a:4:{s:4:"name";s:9:"arrowkeys";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:24;a:4:{s:4:"name";s:7:"startat";s:5:"valid";i:0;s:5:"value";s:1:"1";s:4:"type";s:4:"text";}}', 1),
(2, 'CleanHtml', '<ul><li>Reponsive html timeline</li><li>Responsive images in bootstrap styles</li><li>Position of images on panel selectable</li></ul>', 'wgtimelines_timelines_cleanhtml.tpl', 'a:7:{i:0;a:4:{s:4:"name";s:9:"panel_pos";s:5:"valid";i:0;s:5:"value";N;s:4:"type";s:4:"text";}i:1;a:4:{s:4:"name";s:9:"tabletype";s:5:"valid";i:0;s:5:"value";N;s:4:"type";s:4:"text";}i:2;a:4:{s:4:"name";s:8:"imgstyle";s:5:"valid";i:1;s:5:"value";s:13:"img-thumbnail";s:4:"type";s:4:"text";}i:3;a:4:{s:4:"name";s:7:"bgcolor";s:5:"valid";i:1;s:5:"value";s:7:"#EEEEEE";s:4:"type";s:5:"color";}i:4;a:4:{s:4:"name";s:9:"fontcolor";s:5:"valid";i:1;s:5:"value";s:7:"#000000";s:4:"type";s:5:"color";}i:5;a:4:{s:4:"name";s:12:"panel_imgpos";s:5:"valid";i:1;s:5:"value";s:3:"top";s:4:"type";s:4:"text";}i:6;a:4:{s:4:"name";s:10:"badgecolor";s:5:"valid";i:1;s:5:"value";s:7:"#FFFFFF";s:4:"type";s:5:"color";}}', 2),
(3, 'Simple', '<ul><li>Reponsive bootstrap timeline</li><li>Responsive images in bootstrap styles</li><li>Position of images on panel selectable</li></ul>', 'wgtimelines_timelines_simple.tpl', 'a:17:{i:0;a:4:{s:4:"name";s:9:"panel_pos";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:1;a:4:{s:4:"name";s:9:"tabletype";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:2;a:4:{s:4:"name";s:12:"panel_imgpos";s:5:"valid";i:1;s:5:"value";s:3:"top";s:4:"type";s:4:"text";}i:3;a:4:{s:4:"name";s:8:"imgstyle";s:5:"valid";i:1;s:5:"value";s:13:"img-thumbnail";s:4:"type";s:4:"text";}i:4;a:4:{s:4:"name";s:7:"bgcolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:5;a:4:{s:4:"name";s:9:"fontcolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:6;a:4:{s:4:"name";s:10:"badgecolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:7;a:4:{s:4:"name";s:11:"orientation";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:8;a:4:{s:4:"name";s:10:"datesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:9;a:4:{s:4:"name";s:11:"issuesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:10;a:4:{s:4:"name";s:18:"issuestransparency";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:11;a:4:{s:4:"name";s:23:"issuestransparencyspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:12;a:4:{s:4:"name";s:8:"autoplay";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:13;a:4:{s:4:"name";s:17:"autoplaydirection";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:14;a:4:{s:4:"name";s:13:"autoplaypause";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:15;a:4:{s:4:"name";s:9:"arrowkeys";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:16;a:4:{s:4:"name";s:7:"startat";s:5:"valid";i:0;s:5:"value";s:1:"1";s:4:"type";s:4:"text";}}', 3),
(4, 'Colorful', '<ul><li>Reponsive bootstrap timeline</li><li>Responsive images in bootstrap styles</li><li>Position of images on panel selectable</li></ul>', 'wgtimelines_timelines_colorful.tpl', 'a:25:{i:0;a:4:{s:4:"name";s:9:"tabletype";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:1;a:4:{s:4:"name";s:9:"panel_pos";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:2;a:4:{s:4:"name";s:12:"panel_imgpos";s:5:"valid";i:1;s:5:"value";s:6:"bottom";s:4:"type";s:4:"text";}i:3;a:4:{s:4:"name";s:8:"imgstyle";s:5:"valid";i:1;s:5:"value";s:13:"img-thumbnail";s:4:"type";s:4:"text";}i:4;a:4:{s:4:"name";s:7:"bgcolor";s:5:"valid";i:1;s:5:"value";s:7:"#FF6600";s:4:"type";s:5:"color";}i:5;a:4:{s:4:"name";s:9:"fontcolor";s:5:"valid";i:1;s:5:"value";s:7:"#440000";s:4:"type";s:5:"color";}i:6;a:4:{s:4:"name";s:10:"badgestyle";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:7;a:4:{s:4:"name";s:10:"badgecolor";s:5:"valid";i:1;s:5:"value";s:7:"#FF6600";s:4:"type";s:5:"color";}i:8;a:4:{s:4:"name";s:14:"badgefontcolor";s:5:"valid";i:0;s:5:"value";s:7:"#eeeeee";s:4:"type";s:5:"color";}i:9;a:4:{s:4:"name";s:9:"linecolor";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:5:"color";}i:10;a:4:{s:4:"name";s:11:"borderwidth";s:5:"valid";i:0;s:5:"value";s:3:"1px";s:4:"type";s:4:"text";}i:11;a:4:{s:4:"name";s:11:"borderstyle";s:5:"valid";i:0;s:5:"value";s:5:"solid";s:4:"type";s:4:"text";}i:12;a:4:{s:4:"name";s:11:"bordercolor";s:5:"valid";i:0;s:5:"value";s:7:"#eeeeee";s:4:"type";s:5:"color";}i:13;a:4:{s:4:"name";s:12:"borderradius";s:5:"valid";i:0;s:5:"value";s:3:"5px";s:4:"type";s:4:"text";}i:14;a:4:{s:4:"name";s:9:"boxshadow";s:5:"valid";i:0;s:5:"value";s:23:"5px 5px 5px 5px #eeeeee";s:4:"type";s:4:"text";}i:15;a:4:{s:4:"name";s:11:"orientation";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:16;a:4:{s:4:"name";s:10:"datesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:17;a:4:{s:4:"name";s:11:"issuesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:18;a:4:{s:4:"name";s:18:"issuestransparency";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:19;a:4:{s:4:"name";s:23:"issuestransparencyspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:20;a:4:{s:4:"name";s:8:"autoplay";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:21;a:4:{s:4:"name";s:17:"autoplaydirection";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:22;a:4:{s:4:"name";s:13:"autoplaypause";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:23;a:4:{s:4:"name";s:9:"arrowkeys";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:24;a:4:{s:4:"name";s:7:"startat";s:5:"valid";i:0;s:5:"value";s:1:"1";s:4:"type";s:4:"text";}}', 4),
(5, 'Extended', '<ul><li>Reponsive bootstrap timeline</li><li>Responsive images in bootstrap styles</li><li>Position of images on panel selectable</li></ul>', 'wgtimelines_timelines_extended.tpl', 'a:25:{i:0;a:4:{s:4:"name";s:9:"tabletype";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:1;a:4:{s:4:"name";s:9:"panel_pos";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:2;a:4:{s:4:"name";s:12:"panel_imgpos";s:5:"valid";i:1;s:5:"value";s:6:"bottom";s:4:"type";s:4:"text";}i:3;a:4:{s:4:"name";s:8:"imgstyle";s:5:"valid";i:1;s:5:"value";s:13:"img-thumbnail";s:4:"type";s:4:"text";}i:4;a:4:{s:4:"name";s:7:"bgcolor";s:5:"valid";i:1;s:5:"value";s:7:"#FFFFFF";s:4:"type";s:5:"color";}i:5;a:4:{s:4:"name";s:9:"fontcolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:6;a:4:{s:4:"name";s:10:"badgestyle";s:5:"valid";i:1;s:5:"value";s:4:"full";s:4:"type";s:4:"text";}i:7;a:4:{s:4:"name";s:10:"badgecolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:8;a:4:{s:4:"name";s:14:"badgefontcolor";s:5:"valid";i:1;s:5:"value";s:7:"#FFFFFF";s:4:"type";s:5:"color";}i:9;a:4:{s:4:"name";s:9:"linecolor";s:5:"valid";i:1;s:5:"value";s:7:"#CCCCCC";s:4:"type";s:5:"color";}i:10;a:4:{s:4:"name";s:11:"borderwidth";s:5:"valid";i:1;s:5:"value";s:3:"1px";s:4:"type";s:4:"text";}i:11;a:4:{s:4:"name";s:11:"borderstyle";s:5:"valid";i:1;s:5:"value";s:5:"solid";s:4:"type";s:4:"text";}i:12;a:4:{s:4:"name";s:11:"bordercolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:13;a:4:{s:4:"name";s:12:"borderradius";s:5:"valid";i:1;s:5:"value";s:3:"5px";s:4:"type";s:4:"text";}i:14;a:4:{s:4:"name";s:9:"boxshadow";s:5:"valid";i:1;s:5:"value";s:23:"2px 2px 4px 1px #CCCCCC";s:4:"type";s:4:"text";}i:15;a:4:{s:4:"name";s:11:"orientation";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:16;a:4:{s:4:"name";s:10:"datesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:17;a:4:{s:4:"name";s:11:"issuesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:18;a:4:{s:4:"name";s:18:"issuestransparency";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:19;a:4:{s:4:"name";s:23:"issuestransparencyspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:20;a:4:{s:4:"name";s:8:"autoplay";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:21;a:4:{s:4:"name";s:17:"autoplaydirection";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:22;a:4:{s:4:"name";s:13:"autoplaypause";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:23;a:4:{s:4:"name";s:9:"arrowkeys";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:24;a:4:{s:4:"name";s:7:"startat";s:5:"valid";i:0;s:5:"value";s:1:"1";s:4:"type";s:4:"text";}}', 5),
(6, 'Big Picture', '<ul><li>Reponsive bootstrap timeline</li><li>Responsive images in bootstrap styles</li><li>Position of images on panel selectable</li></ul>', 'wgtimelines_timelines_bigpicture.tpl', 'a:17:{i:0;a:4:{s:4:"name";s:9:"panel_pos";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:1;a:4:{s:4:"name";s:9:"tabletype";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:2;a:4:{s:4:"name";s:12:"panel_imgpos";s:5:"valid";i:1;s:5:"value";s:3:"top";s:4:"type";s:4:"text";}i:3;a:4:{s:4:"name";s:8:"imgstyle";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:4;a:4:{s:4:"name";s:7:"bgcolor";s:5:"valid";i:1;s:5:"value";s:7:"#EEEEEE";s:4:"type";s:5:"color";}i:5;a:4:{s:4:"name";s:9:"fontcolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:6;a:4:{s:4:"name";s:10:"badgecolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:7;a:4:{s:4:"name";s:11:"orientation";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:8;a:4:{s:4:"name";s:10:"datesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:9;a:4:{s:4:"name";s:11:"issuesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:10;a:4:{s:4:"name";s:18:"issuestransparency";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:11;a:4:{s:4:"name";s:23:"issuestransparencyspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:12;a:4:{s:4:"name";s:8:"autoplay";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:13;a:4:{s:4:"name";s:17:"autoplaydirection";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:14;a:4:{s:4:"name";s:13:"autoplaypause";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:15;a:4:{s:4:"name";s:9:"arrowkeys";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:16;a:4:{s:4:"name";s:7:"startat";s:5:"valid";i:0;s:5:"value";s:1:"1";s:4:"type";s:4:"text";}}', 6),
(7, 'Animated', '<ul><li>Reponsive timeline</li><li>Responsive images in bootstrap styles</li><li>Position of images on panel selectable</li><li>Fade-In animation on scrolling</li></ul>', 'wgtimelines_timelines_animated.tpl', 'a:17:{i:0;a:4:{s:4:"name";s:9:"panel_pos";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:1;a:4:{s:4:"name";s:9:"tabletype";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:2;a:4:{s:4:"name";s:12:"panel_imgpos";s:5:"valid";i:1;s:5:"value";s:6:"bottom";s:4:"type";s:4:"text";}i:3;a:4:{s:4:"name";s:8:"imgstyle";s:5:"valid";i:1;s:5:"value";s:10:"img-circle";s:4:"type";s:4:"text";}i:4;a:4:{s:4:"name";s:7:"bgcolor";s:5:"valid";i:1;s:5:"value";s:7:"#CCCCFF";s:4:"type";s:5:"color";}i:5;a:4:{s:4:"name";s:9:"fontcolor";s:5:"valid";i:1;s:5:"value";s:7:"#FFFFFF";s:4:"type";s:5:"color";}i:6;a:4:{s:4:"name";s:10:"badgecolor";s:5:"valid";i:1;s:5:"value";s:7:"#337ab7";s:4:"type";s:5:"color";}i:7;a:4:{s:4:"name";s:11:"orientation";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:8;a:4:{s:4:"name";s:10:"datesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:9;a:4:{s:4:"name";s:11:"issuesspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:10;a:4:{s:4:"name";s:18:"issuestransparency";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:11;a:4:{s:4:"name";s:23:"issuestransparencyspeed";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:12;a:4:{s:4:"name";s:8:"autoplay";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:13;a:4:{s:4:"name";s:17:"autoplaydirection";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:14;a:4:{s:4:"name";s:13:"autoplaypause";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:15;a:4:{s:4:"name";s:9:"arrowkeys";s:5:"valid";i:0;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:16;a:4:{s:4:"name";s:7:"startat";s:5:"valid";i:0;s:5:"value";s:1:"1";s:4:"type";s:4:"text";}}', 7),
(8, 'Slider', '<ul><li>jquery slider timeline</li><li>vertical or horizontal timeline</li><li>Autoplay option</li><li>Not fully responsive</li><li>Images in bootstrap styles</li><li>Position of images on panel selectable</li></ul>', 'wgtimelines_timelines_slider.tpl', 'a:17:{i:0;a:4:{s:4:"name";s:9:"panel_pos";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:1;a:4:{s:4:"name";s:9:"tabletype";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:2;a:4:{s:4:"name";s:12:"panel_imgpos";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:3;a:4:{s:4:"name";s:8:"imgstyle";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:4:"text";}i:4;a:4:{s:4:"name";s:7:"bgcolor";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:5:"color";}i:5;a:4:{s:4:"name";s:9:"fontcolor";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:5:"color";}i:6;a:4:{s:4:"name";s:10:"badgecolor";s:5:"valid";i:0;s:5:"value";s:0:"";s:4:"type";s:5:"color";}i:7;a:4:{s:4:"name";s:11:"orientation";s:5:"valid";i:1;s:5:"value";s:8:"vertical";s:4:"type";s:4:"text";}i:8;a:4:{s:4:"name";s:10:"datesspeed";s:5:"valid";i:1;s:5:"value";s:3:"500";s:4:"type";s:4:"text";}i:9;a:4:{s:4:"name";s:11:"issuesspeed";s:5:"valid";i:1;s:5:"value";s:4:"1000";s:4:"type";s:4:"text";}i:10;a:4:{s:4:"name";s:18:"issuestransparency";s:5:"valid";i:1;s:5:"value";s:3:"0.9";s:4:"type";s:4:"text";}i:11;a:4:{s:4:"name";s:23:"issuestransparencyspeed";s:5:"valid";i:1;s:5:"value";s:4:"1000";s:4:"type";s:4:"text";}i:12;a:4:{s:4:"name";s:8:"autoplay";s:5:"valid";i:1;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:13;a:4:{s:4:"name";s:17:"autoplaydirection";s:5:"valid";i:1;s:5:"value";s:7:"forward";s:4:"type";s:4:"text";}i:14;a:4:{s:4:"name";s:13:"autoplaypause";s:5:"valid";i:1;s:5:"value";s:4:"1000";s:4:"type";s:4:"text";}i:15;a:4:{s:4:"name";s:9:"arrowkeys";s:5:"valid";i:1;s:5:"value";s:5:"false";s:4:"type";s:4:"bool";}i:16;a:4:{s:4:"name";s:7:"startat";s:5:"valid";i:1;s:5:"value";s:1:"1";s:4:"type";s:4:"text";}}', 8);
